name: record_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  # core
  flutter_dotenv: ^5.1.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  get_it: ^8.0.3
  injectable: ^2.5.0
  # redux
  redux: ^5.0.0
  flutter_redux: ^0.10.0
  redux_thunk: ^0.4.0
  reselect: ^0.5.0
  # network
  dio: ^5.2.1+1
  http_parser: ^4.0.2
  # ui
  auto_route: ^10.0.1
  gif: ^2.3.0
  layout: ^1.0.5
  # localization
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  freezed: ^3.0.4
  auto_route_generator: ^10.0.1
  injectable_generator: ^2.6.2
  retrofit_generator: ^9.1.9
  json_serializable: ^6.7.1
  flutter_lints: ^3.0.1
  flutter_gen: ^5.8.0

flutter_gen:
  output: lib/generated/flutter_gen/
  line_length: 100
  
  integrations:
    flutter_svg: true

flutter:
  generate: true
  uses-material-design: true
  
  assets:
    - assets/pdfs/
    - assets/images/
    - assets/env/